# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1210/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1210/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hzycpp/Desktop/MyTemplate/noobnet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hzycpp/Desktop/MyTemplate/noobnet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1186/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1210/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzycpp/Desktop/MyTemplate/noobnet/CMakeFiles /home/hzycpp/Desktop/MyTemplate/noobnet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hzycpp/Desktop/MyTemplate/noobnet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named noobnet

# Build rule for target.
noobnet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 noobnet
.PHONY : noobnet

# fast build rule for target.
noobnet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/build
.PHONY : noobnet/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

net/config.o: net/config.cc.o
.PHONY : net/config.o

# target to build an object file
net/config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/config.cc.o
.PHONY : net/config.cc.o

net/config.i: net/config.cc.i
.PHONY : net/config.i

# target to preprocess a source file
net/config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/config.cc.i
.PHONY : net/config.cc.i

net/config.s: net/config.cc.s
.PHONY : net/config.s

# target to generate assembly for a file
net/config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/config.cc.s
.PHONY : net/config.cc.s

net/log.o: net/log.cc.o
.PHONY : net/log.o

# target to build an object file
net/log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/log.cc.o
.PHONY : net/log.cc.o

net/log.i: net/log.cc.i
.PHONY : net/log.i

# target to preprocess a source file
net/log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/log.cc.i
.PHONY : net/log.cc.i

net/log.s: net/log.cc.s
.PHONY : net/log.s

# target to generate assembly for a file
net/log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/log.cc.s
.PHONY : net/log.cc.s

net/mutex.o: net/mutex.cc.o
.PHONY : net/mutex.o

# target to build an object file
net/mutex.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/mutex.cc.o
.PHONY : net/mutex.cc.o

net/mutex.i: net/mutex.cc.i
.PHONY : net/mutex.i

# target to preprocess a source file
net/mutex.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/mutex.cc.i
.PHONY : net/mutex.cc.i

net/mutex.s: net/mutex.cc.s
.PHONY : net/mutex.s

# target to generate assembly for a file
net/mutex.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/mutex.cc.s
.PHONY : net/mutex.cc.s

net/thread.o: net/thread.cc.o
.PHONY : net/thread.o

# target to build an object file
net/thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/thread.cc.o
.PHONY : net/thread.cc.o

net/thread.i: net/thread.cc.i
.PHONY : net/thread.i

# target to preprocess a source file
net/thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/thread.cc.i
.PHONY : net/thread.cc.i

net/thread.s: net/thread.cc.s
.PHONY : net/thread.s

# target to generate assembly for a file
net/thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/thread.cc.s
.PHONY : net/thread.cc.s

net/utils.o: net/utils.cc.o
.PHONY : net/utils.o

# target to build an object file
net/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/utils.cc.o
.PHONY : net/utils.cc.o

net/utils.i: net/utils.cc.i
.PHONY : net/utils.i

# target to preprocess a source file
net/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/utils.cc.i
.PHONY : net/utils.cc.i

net/utils.s: net/utils.cc.s
.PHONY : net/utils.s

# target to generate assembly for a file
net/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/noobnet.dir/build.make CMakeFiles/noobnet.dir/net/utils.cc.s
.PHONY : net/utils.cc.s

tests/test.o: tests/test.cc.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_config.o: tests/test_config.cc.o
.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i
.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s
.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o
.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i
.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s
.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_thread.o: tests/test_thread.cc.o
.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i
.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s
.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... noobnet"
	@echo "... test"
	@echo "... test_config"
	@echo "... test_fiber"
	@echo "... test_thread"
	@echo "... net/config.o"
	@echo "... net/config.i"
	@echo "... net/config.s"
	@echo "... net/log.o"
	@echo "... net/log.i"
	@echo "... net/log.s"
	@echo "... net/mutex.o"
	@echo "... net/mutex.i"
	@echo "... net/mutex.s"
	@echo "... net/thread.o"
	@echo "... net/thread.i"
	@echo "... net/thread.s"
	@echo "... net/utils.o"
	@echo "... net/utils.i"
	@echo "... net/utils.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

